# site name
prefixName: ğŸ¦‹
siteName: BIGOcean's Blog

# favicon and site master avatar

favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://www.cnblogs.com/BIGOcean
description: é¢æœå¤§æµ·ï¼Œæ˜¥æš–èŠ±å¼€ï¼
cdn: https://cdn.jsdelivr.net/gh/bigoceans/cdn
pjax: 1 # å½“ä½ ç‚¹å‡»ä¸€ä¸ªé“¾æ¥ï¼Œä¸æ˜¯é¡µé¢è·³è½¬ï¼Œåªæ˜¯ç«™å†…é¡µé¢åˆ·æ–°ã€‚1å¼€å¯

mathjax: 0 # æ•°å­¦å…¬å¼ 1å¼€å¯

notice: æ¬¢è¿æ¥åˆ°å¤§æµ·çš„åšå®¢
lazyloadImg: https://cdn.jsdelivr.net/gh/bigoceans/cdn/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }

  å½’æ¡£: { path: /archives, fa: fa-archive faa-vertical, submenus: {  
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code },
    å®‰å“: {path: /categories/å®‰å“/, fa: fa-android faa-pulse }, 
    å¾®è½¯: {path: /categories/å¾®è½¯/, fa: fa-windows }, 
    Winè¶£: {path: /categories/Winè¶£/, fa: fa-check },
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o },
    è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book }
  } }

  å­¦ä¹ : { path: /archives, fa: fa-graduation-cap faa-shake , submenus: { 
    è¯­è¨€ç±»: {path: /tags/è¯­è¨€ç±»/, fa: fa-television},
    ç½‘ç»œç±»: {path: /tags/ç½‘ç»œç±»/, fa: fa-edit}, 
    è„šæœ¬ç±»: {path: /tags/è„šæœ¬ç±»/, fa: fa-microchip},
    ç®—æ³•ç±»: {path: /tags/ç®—æ³•ç±»/, fa: fa-bank}
  } }

  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce }, 
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical }, 
    æ­Œå•: {path: /music/, fa: fa-headphones faa-bounce },
    å›¾é›†: {path:  https://bigocean1.lofter.com, fa: fa-photo faa-vertical},
    è§†é¢‘: {path: https://bigoceana.gitee.io/videos, fa: fa-play-circle faa-bounce }
  } }

  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  å¼¹å¹•: { path: https://bigoceana.gitee.io/bigocean111/ , fa: fa-comments } 
  èµèµ: { path: /donate/, fa: fa-heartbeat faa-tada }
  å…³äº: { path: javascript:;, fa: fa-vcard faa-tada, submenus: {
    æˆ‘çš„: {path: /about/, fa: fa-user faa-tada},
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-vertical }

  


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/1bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/2bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/3bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/4bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/5bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/6bg.webp
  - https://gitee.com/bigoceana/cdn/raw/master/img/bg/7bg.webp

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-dot

# startdash é¢æ¿url, title, desc img
startdash: 
  - {url: https://8r0suy.coding-pages.com, title: çˆ±å¿ƒæ ‘, desc: ä¸€ä¸ªç§˜å¯†çš„åœ°æ–¹, img: /img/startpics/2.jpg}
  - {url: https://66qxqw.coding-pages.com/, title: å°æ¸¸æˆ, desc: å„ç§æœ‰è¶£çš„å°æ¸¸æˆå…¨åœ¨è¿™é‡Œå•¦, img: /img/startpics/1.jpg}
  - {url: https://uh2ys4.coding-pages.com/, title: å¯¼èˆªé¡µ, desc: å„ç§æœ‰ç”¨çš„ç½‘é¡µé›†åˆå…¨åœ¨è¿™é‡Œå•¦, img: /img/link/4.jpg}



# your site build time or founded date
siteBuildingTime: 02/28/2020

#social  url, img PCç«¯é…ç½®
social:
  GitHub: {url: https://github.com/bigoceans/, img: /img/social/github.png}
  æ–°æµª: {url: https://weibo.com/p/1005052816637892/home?from=page_100505&mod=TAB&is_all=1#place, img: /img/social/sina.png}
  QQéŸ³ä¹: {url: https://y.qq.com/n/yqq/playlist/6970849799.html, img: /img/social/qqmusic.png}
  çŸ¥ä¹: {url: https://www.zhihu.com/people/da-hai-54-28, img: /img/social/zhihu.png}
  é‚®ç®±: {url: https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=E3F6dHxwdnJ9IlNlemM9YmI9cHx_ ,  img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/weixing.png, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: https://github.com/bigoceans/, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/p/1005052816637892/home?from=page_100505&mod=TAB&is_all=1#place, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1647383460&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal:  https://cdn.jsdelivr.net/gh/bigoceans/cdn/img/cnblogs/WeChanQR.jpg
  alipay: /img/custom/alipay.jpg
  wechat: /img/custom/wechat.png
  wechatSQ: /img/custom/weixing.png

# è§†é¢‘
movies:
  url: https://cdn.jsdelivr.net/gh/bigoceans/video
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: mv.mp4,unbroken.mp4

aplayer: 
  id: 6970849799 # ç½‘æ˜“æ­Œå•ï¼š4934609313 è…¾è®¯æ­Œå•ï¼š6970849799
  server: tencent # éŸ³ä¹å¹³å°: netease, tencent, kugou, xiami, baidu
  type: playlist # song, playlist, album, search, artist
  fixed: true # å¼€å¯å›ºå®šæ¨¡å¼
  mini: true #è¿·ä½ æ¨¡å¼
  autoplay: false #è‡ªåŠ¨æ’­æ”¾ï¼Œç§»åŠ¨ç«¯å¯èƒ½å‡ºbug
  loop: all #å¾ªç¯æ’­æ”¾æ¨¡å¼ï¼šall, one,none
  order: random #æ’­æ”¾é¡ºåºï¼šlist, random
  preload: none #éŸ³ä¹æ–‡ä»¶é¢„è½½å…¥æ¨¡å¼ï¼Œå¯é€‰é¡¹ï¼š none, metadata, auto
  volume: 0.7 #åˆå§‹éŸ³é‡
  mutex: true # è¯¥é€‰é¡¹å¼€å¯æ—¶ï¼Œå¦‚æœåŒé¡µé¢æœ‰å…¶ä»– aplayer æ’­æ”¾ï¼Œè¯¥æ’­æ”¾å™¨ä¼šæš‚åœ
  theme: #f7acbc #æ’­æ”¾å™¨é¢œè‰²


# Online contact ##åœ¨çº¿èŠå¤©
daovoice: true
daovoice_app_id: c38f5719 ##è¿™é‡Œæ›¿æ¢æˆä½ DaoVoiceä¸Šçš„appid

#2dæ¿å¨˜
live2d:
  enable: true

# Local search æœç´¢
local_search:
  enable: true

# è¯„è®ºç³»ç»Ÿ
# Valine ##æç®€ç•™è¨€åŠŸèƒ½
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
valine:
  enable: true ##æ‰“å¼€valineè¯„è®ºåŠŸèƒ½true
  appId: hEvISJNEVpYHJM50anGRr26y-gzGzoHsz
  appKey: Tlg7cokSVVOikjKN7DK5XUWr
  notify: false #è¯„è®ºmailå›å¤æé†’
  verify: true #éªŒè¯ç 
  visitor: false #ç»Ÿè®¡é˜…è¯»é‡
  comment_count: true #ç»Ÿè®¡è¯„è®ºæ•°
  avatar: monsterid # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  palaceholder: ä½ æ˜¯æˆ‘ä¸€ç”Ÿåªä¼šé‡è§ä¸€æ¬¡çš„æƒŠå–œ # Comment Box placeholder